// Package apidocs embeds the generated OpenAPI spec for serving at runtime.
// swagger.json / swagger.yaml are generated by `make docs` (swaggo); this file
// is hand-written and must not be removed by regeneration.
package apidocs

import _ "embed"

// SpecJSON is the generated OpenAPI 2.0 spec, served verbatim at /openapi.json.
//
//go:embed swagger.json
var SpecJSON []byte
